services:
  db:
    image: mysql:5.7
    container_name: mysql_taller
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /raid0/ftpsv/ftp/Docker/volumes/gestiontallerpfc_mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web

  api:
    build: ./taller-back-api
    container_name: api_taller
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_STARTTLS: ${MAIL_STARTTLS}
      MAIL_SSL_TLS: ${MAIL_SSL_TLS}
      USE_CREDENTIALS: ${USE_CREDENTIALS}
      VALIDATE_CERTS: ${VALIDATE_CERTS}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api_taller.rule=Host(`anthonyx82.ddns.net`) && PathPrefix(`/taller/api`)"
      - "traefik.http.routers.api_taller.entrypoints=websecure"
      - "traefik.http.routers.api_taller.tls.certresolver=mysresolver"
      - "traefik.http.middlewares.api_taller_stripprefix.stripprefix.prefixes=/taller/api"
      - "traefik.http.routers.api_taller.middlewares=api_taller_stripprefix"
      - "traefik.http.services.api_taller.loadbalancer.server.port=8000"

  frontend:
    build: ./taller-front
    container_name: angular_taller
    restart: always
    depends_on:
      - api
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend_taller.rule=Host(`anthonyx82.ddns.net`) && PathPrefix(`/taller-front`)"
      - "traefik.http.routers.frontend_taller.entrypoints=websecure"
      - "traefik.http.routers.frontend_taller.tls.certresolver=mysresolver"
      - "traefik.http.middlewares.frontend_taller_stripprefix.stripprefix.prefixes=/taller-front"
      - "traefik.http.routers.frontend_taller.middlewares=frontend_taller_stripprefix"
      - "traefik.http.services.frontend_taller.loadbalancer.server.port=80"

networks:
  web:
    external: true
